### ISSUE TITLE
Only recurse for unseen messages

### ISSUE THREAD

**Issue by naterush** [sigp/cbc-casper-js#2]
It seems that when a new message is verified and stored, all the messages in its justification are as well, and all the messages in these messages justifications are as well, etc (happens [here](https://github.com/sigp/cbc-casper-js/blob/master/validators/index.js#L162)).

I don't think we have to recurse all the way through the justifications - just down until we bump into messages we know. So I think it suffices to only recurse if `!this.isMessageKnown`, or something similar. This will stop a validator from doing to much extra work. 

Another option is to add a function `getNewMessages(msg)` that recurses through a justification, and grabs all the messages that are not known yet, and then adding them all in one go. It might make the recursion easier to follow - but it's just a style thing here, so do what you think is best. 

It's also possible I'm misunderstanding the code properly - in which case let me know :)

**Comment by paulhauner** [comment]
Oh, interesting! It was certainly my intention to do minimal recursion.

I’m about to jump on a plane, but I’ll check this out when I get home 🙂

Thanks for your input, Nate!

**Comment by paulhauner** [comment]
Oh yep, you're right. I am doing an unnecessary recursion here.

Unfortunately I have to recurse down the tree once to get the hashes (I need to know the hashes of all messages in the justifications before I can know the hash of a message). But I don't need to do that second recursion there.

I have been thinking about implementing a "common database" between all validators to speed up simulations (i.e., a shared hash table). That way messages can be sent just as hashes, reducing the duplication of data in memory. Each validator would then maintain it's own list of "trusted message hashes".

I figure such a database can be emulated in real-world situation (with some latency) and would not reduce for the "realism" of the simulator. Keen to hear if you think otherwise. 

Paul.
